name: Workflow file for Testing-repo-4

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: docker build --pull -t ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
        
      - name: Deploy to AWS
        uses: appleboy/ssh-action@latest
        with:
          host: ${{secrets.AWS_HOSTNAME}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull {{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker run --name backend -d ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker image prune -f
