name: Workflow file for Testing-repo-4

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: docker build --pull -t ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
        
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.AWS_HOSTNAME}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          script: |
            docker stop backend-1 || true
            docker rm backend-1 || true
            docker stop backend-2 || true
            docker rm backend-2 || true
            docker stop backend-3 || true
            docker rm backend-3 || true
            docker stop backend-4 || true
            docker rm backend-4 || true
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker run --name backend-1 -d --env-file ${{secrets.ENV_PATH}} -p ${{secrets.DOCKERHUB_PORT_OUTSIDE}}:3000 ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker run --name backend-2 -d --env-file ${{secrets.ENV_PATH}} -p ${{secrets.DOCKERHUB_PORT_OUTSIDE}}:3001 ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker run --name backend-3 -d --env-file ${{secrets.ENV_PATH}} -p ${{secrets.DOCKERHUB_PORT_OUTSIDE}}:3002 ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker run --name backend-4 -d --env-file ${{secrets.ENV_PATH}} -p ${{secrets.DOCKERHUB_PORT_OUTSIDE}}:3003 ${{secrets.DOCKERHUB_USERNAME}}/practice-2:latest
            docker image prune -f
